env:
  node: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:node/recommended'
  - 'plugin:import/recommended'
  - 'prettier'
parserOptions:
  ecmaVersion: 2020
rules:
  no-console: error
  prefer-const: error
  no-var: error
  no-use-before-define: error
  no-await-in-loop: error
